/**
 * Server-side email i18n. Lingui's babel macros require Babel which the
 * Wasp server build doesn't run, so we use a small hand-maintained
 * dictionary for the static newsletter chrome instead. The actual
 * editorial content (subject, dek, items) is generated by the Editor
 * agent in `beat.outputLanguage` and needs no translation here.
 *
 * To add a string: add the key to `STRINGS.en`, then to each other
 * locale. To add a locale: add it to `STRINGS` and ensure templates
 * pass `EmailLocaleProvider locale="<code>"`.
 */
import { createContext, useContext } from "react";

export const STRINGS = {
  en: {
    issue: "Issue",
    whyItMatters: "Why it matters",
    dashboard: "Dashboard",
    pause: "Pause",
    unsubscribe: "Unsubscribe",
    deliveredBy: "Personal Beats · delivered by your agent",
    analysis: "Analysis",
    context: "Context",
    sources: "Sources",
    readMore: "Read more",
    editorsNote: "Editor's note",
  },
  pl: {
    issue: "Wydanie",
    whyItMatters: "Dlaczego to ważne",
    dashboard: "Pulpit",
    pause: "Wstrzymaj",
    unsubscribe: "Wypisz się",
    deliveredBy: "Personal Beats · dostarczone przez Twojego agenta",
    analysis: "Analiza",
    context: "Kontekst",
    sources: "Źródła",
    readMore: "Czytaj dalej",
    editorsNote: "Od redakcji",
  },
} as const;

export type EmailLocale = keyof typeof STRINGS;
export type EmailStringKey = keyof typeof STRINGS["en"];

export function isEmailLocale(value: string | null | undefined): value is EmailLocale {
  return value !== null && value !== undefined && value in STRINGS;
}

export function tEmail(locale: string | null | undefined, key: EmailStringKey): string {
  const code = isEmailLocale(locale) ? locale : "en";
  return STRINGS[code][key] ?? STRINGS.en[key];
}

const EmailLocaleContext = createContext<EmailLocale>("en");
export const EmailLocaleProvider = EmailLocaleContext.Provider;

export function useEmailLocale(): EmailLocale {
  return useContext(EmailLocaleContext);
}

export function useEmailT(): (key: EmailStringKey) => string {
  const locale = useEmailLocale();
  return (key) => tEmail(locale, key);
}
